#
TOP="../../.."
AIDLCMD="$TOP/out/host/linux-x86/obj/EXECUTABLES/aidlcpp_intermediates/aidlcpp -I$TOP/frameworks/base/core/java/ -I. "
$AIDLCMD -owork aidl/android/os/IPowerManager.aidl 
$AIDLCMD -owork aidl/android/os/IPermissionController.aidl 
$AIDLCMD -owork aidl/android/os/ISchedulingPolicyService.aidl
$AIDLCMD -owork aidl/IWifiClient.aidl
$AIDLCMD -owork aidl/IWifiService.aidl
$AIDLCMD -owork extra/IEffectClient.aidl
$AIDLCMD -owork extra/IAudioFlinger.aidl
$AIDLCMD -owork extra/IAudioFlingerClient.aidl
$AIDLCMD -owork extra/IAudioPolicyService.aidl
$AIDLCMD -owork extra/IAudioRecord.aidl
$AIDLCMD -owork extra/IAudioTrack.aidl
$AIDLCMD -owork extra/ICamera.aidl
$AIDLCMD -owork extra/ICameraClient.aidl
$AIDLCMD -owork extra/ICameraRecordingProxy.aidl
$AIDLCMD -owork extra/ICameraRecordingProxyListener.aidl
$AIDLCMD -owork extra/ICameraService.aidl
$AIDLCMD -owork extra/ICommonClock.aidl
$AIDLCMD -owork extra/ICommonClockListener.aidl
$AIDLCMD -owork extra/ICommonTimeConfig.aidl
$AIDLCMD -owork extra/ICrypto.aidl
$AIDLCMD -owork extra/IDisplayEventConnection.aidl
$AIDLCMD -owork extra/IDrmManagerService.aidl
$AIDLCMD -owork extra/IDrmServiceListener.aidl
$AIDLCMD -owork extra/IEffect.aidl
$AIDLCMD -owork extra/IGraphicBufferAlloc.aidl
$AIDLCMD -owork extra/IMediaMetadataRetriever.aidl
$AIDLCMD -owork extra/IMediaPlayer.aidl
$AIDLCMD -owork extra/IMediaPlayerClient.aidl
$AIDLCMD -owork extra/IMediaPlayerService.aidl
$AIDLCMD -owork extra/IMediaRecorder.aidl
$AIDLCMD -owork extra/IMediaRecorderClient.aidl
$AIDLCMD -owork extra/IMemory.aidl
$AIDLCMD -owork extra/IMemoryHeap.aidl
$AIDLCMD -owork extra/IMountService.aidl
$AIDLCMD -owork extra/IMountServiceListener.aidl
$AIDLCMD -owork extra/IMountShutdownObserver.aidl
$AIDLCMD -owork extra/IObbActionListener.aidl
$AIDLCMD -owork extra/IOMX.aidl
$AIDLCMD -owork extra/IOMXObserver.aidl
$AIDLCMD -owork extra/IPhoneClient.aidl
$AIDLCMD -owork extra/IPhoneService.aidl
$AIDLCMD -owork extra/ISensorEventConnection.aidl
$AIDLCMD -owork extra/ISensorServer.aidl
$AIDLCMD -owork extra/IServiceManager.aidl
$AIDLCMD -owork extra/IStreamListener.aidl
$AIDLCMD -owork extra/IStreamSource.aidl
$AIDLCMD -owork extra/ISurface.aidl
$AIDLCMD -owork extra/ISurfaceComposer.aidl
$AIDLCMD -owork extra/ISurfaceComposerClient.aidl
$AIDLCMD -owork extra/ISurfaceTexture.aidl
